[package]
name = "vulkan-tutorial"
version = "0.1.0"
authors = ["kbone <kbonehobby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.18.0"
winit = "0.22.0"
